### ISSUE TITLE
Consider using enums for states in GameWIn

### ISSUE THREAD

**Issue by JVViacrusis** [COMP2522/project-yumo-john-lucas-viet#108]
https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/f7736a6b3aa8f6f68f4e7cb1c180d02938678b87/src/main/java/org/myProject/GameWin.java#L90-L131

Might make it more clear if you use enums here

**Comment by LucasHYing** [comment]
resolved, but we considered to stay with if statement
