### ISSUE TITLE
Refactor or clarify count and redraws

### ISSUE THREAD

**Issue by JVViacrusis** [COMP2522/project-yumo-john-lucas-viet#109]
https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/f7736a6b3aa8f6f68f4e7cb1c180d02938678b87/src/main/java/org/myProject/GameWin.java#L133-L155

Unclear what count is for. Decleration comment mentions 'redraws for the game' but it isn't super clear what that means. This may require refactoring to a system that is more clear, or some form of documentation linked in the comment

**Comment by LucasHYing** [comment]
fixed
