### ISSUE TITLE
Enforce usage of CollisionDetection.java interface

### ISSUE THREAD

**Issue by JVViacrusis** [COMP2522/project-yumo-john-lucas-viet#114]
https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/f7736a6b3aa8f6f68f4e7cb1c180d02938678b87/src/main/java/org/myProject/obj/BulletObj.java#L28-L31\

CollisionDetection.java provides a method very similar to this one. A lot of other classes that seem to need collision detection also do not use this interface

**Comment by LucasHYing** [comment]
completed
