### ISSUE TITLE
Remove magic numbers

### ISSUE THREAD

**Issue by 7374179** [COMP2522/project-yumo-john-lucas-viet#29]
https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/77ac8aebb3f7c459ff871b9bf1c56cbe2c52007f/src/main/java/org/myProject/obj/PlaneObj.java#L322

https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/77ac8aebb3f7c459ff871b9bf1c56cbe2c52007f/src/main/java/org/myProject/obj/PlaneObj.java#L323

https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/77ac8aebb3f7c459ff871b9bf1c56cbe2c52007f/src/main/java/org/myProject/obj/PlaneObj.java#L324

https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/77ac8aebb3f7c459ff871b9bf1c56cbe2c52007f/src/main/java/org/myProject/obj/PlaneObj.java#L325

https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/77ac8aebb3f7c459ff871b9bf1c56cbe2c52007f/src/main/java/org/myProject/obj/PlaneObj.java#L326

**Comment by John2T** [comment]
Shoot function has been modified had magic num issues have been fixed
