### ISSUE TITLE
Why are these null? Refactor to remove null

### ISSUE THREAD

**Issue by pbucci** [COMP2522/project-yumo-john-lucas-viet#38]
https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/77ac8aebb3f7c459ff871b9bf1c56cbe2c52007f/src/main/java/org/myProject/obj/PlayerUIObj.java#L68

**Comment by John2T** [comment]
Fixed and changed to the following

  int playerWidth = player.width;
    int playerHeight = player.height;
