### ISSUE TITLE
Javadocs for different shot types

### ISSUE THREAD

**Issue by JVViacrusis** [COMP2522/project-yumo-john-lucas-viet#58]
https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/77ac8aebb3f7c459ff871b9bf1c56cbe2c52007f/src/main/java/org/myProject/obj/PlaneObj.java#L318-L346

Adding javadocs describing the shot style may also allow someone else to pick up this feature sooner.

**Comment by John2T** [comment]
Added Javadocs to each shot style.
Removed the beam() option
