### ISSUE TITLE
Inconsistent interface naming

### ISSUE THREAD

**Issue by JVViacrusis** [COMP2522/project-yumo-john-lucas-viet#70]
[CollisionDetection.java](https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/main/src/main/java/org/myProject/Interfaces/CollisionDetection.java)
[Drawable.java](https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/main/src/main/java/org/myProject/Interfaces/Drawable.java)

Might cause confusion while reading through the code. Consider renaming CollisionDetection.java to follow the [Verb]able.java naming convention

**Comment by LucasHYing** [comment]
fixed
