### ISSUE TITLE
Dividing Health by 1.0 is unnecessary

### ISSUE THREAD

**Issue by YejuJ** [COMP2522/project-yumo-john-lucas-viet#76]
https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/4a5d15650abe6b9a041e7d6d9de6e29e26de6810/src/main/java/org/myProject/obj/PlayerUIObj.java#L39

**Comment by John2T** [comment]
Changed one to a constant called MAX_HEALTH which is 100.
Now when we get player health we can divide by 100 to find the health percentage.
