### ISSUE TITLE
Variable is already assigned to this value

### ISSUE THREAD

**Issue by 7374179** [COMP2522/project-yumo-john-lucas-viet#81]
https://github.com/COMP2522/project-yumo-john-lucas-viet/blob/4a5d15650abe6b9a041e7d6d9de6e29e26de6810/src/main/java/org/myProject/obj/PlaneObj.java#L267

**Comment by John2T** [comment]
Removed line 262 health = 1;

Changed this.health = 1 to this.health = 100;

Upon respawning we are not creating a new player instance but instead decreasing lives by 1 and resetting the health back to 100
